<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.workflow.bpmn4j</groupId>
        <artifactId>bpmn4j-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>bpmn4j-adk</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>bpmn4j-adk-integration-python</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.workflow.bpmn4j</groupId>
                <artifactId>bpmn4j-langgraph-translator</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.workflow.bpmn4j</groupId>
                <artifactId>bpmn4j-langgraph-runtime</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>